cam_model: EquidistantCamera
cam_width: 720
cam_height: 540
scale: 1.0
cam_fx: 351.31400364193297
cam_fy: 351.4911744656785
cam_cx: 367.8522793375995
cam_cy: 253.8402144980996
k1: -0.03696737352869157
k2: -0.008917880497032812
k3: 0.008912969593422046
k4: -0.0037685977496087313
